### ISSUE TITLE
[Feature request] Allow LOG to be defined as a no-op by a macro definition

### ISSUE THREAD

**Issue by jgabaut** [khushal-banks/log_bank#29]
At the moment, `TRACE` definition can be "turned-off".

I suggest adding the option to do the same, so that user-code can define its own logic using a library-provided macro.

Such a macro could be used in an `#ifdef` to change `LOG` definition.

On this, I recall someone else suggesting turning the alternative definitions from `NULL` to `(void*)0`. Does this make any difference?
  - Edit: it was in #1

**Comment by khushal-banks** [comment]
Library works in two modes.
1. Debug Mode - Used while product is being developed.
2. Release Mode - Used when product is being shipped. So, customers of your application will always have Release mode binary.

# Features of these modes
1. TRACE macro is only available in Debug mode. So anything that you don't want your customers to see should be logged using TRACE macro. TRACE macro is automatically replaced with NULL in Release mode. So developers can use TRACE macro to trace issues using this macro ... customer will never see these information.
2. LOG macro is available in both modes. So anything that you want to be visible to your customers should be logged using LOG macro. So both customers and developers will see these information.

# How to compile in different modes.

Add following steps in your compilation process:
1. Debug Mode
```
-DDEBUG -Llib/log_bank/ -Ilib/include/ -llog_bank_debug
```
2. Release Mode
```
-DNDEBUG -Llib/log_bank/ -Ilib/include/ -llog_bank_release
```

Details about compilation of library can be found in [EXAMPLES.md](https://github.com/khushal-banks/log_bank/blob/main/examples/EXAMPLES.md) which is automatically done using [setup.sh](https://github.com/khushal-banks/log_bank/blob/main/examples/main_example/setup.sh)

# Why to use priority levels?
First argument to both LOG and TRACE macro is the priority level. Details in README [Priority level Support](https://github.com/khushal-banks/log_bank?tab=readme-ov-file#priority-level-support)

Priority levels are used to assign different priority to logged information. LOG and TRACE macro both can ignore log requests based on priority level. If priority level of LOG/TRACE is below configured log level then log request is ignored.

We can use `log_set_level(int level)` function to control this filter. Allowing us to control which information we see.

By default, 
- Debug Mode has configured LOG_INFO as log level. So, you see almost all logs. Only, logs with priority level LOG_DEBUG 
are ignored. You can always change level using `log_set_level` to change this behavior.
- Release Mode has configured LOG_ERROR as log level. So, logs with priority level LOG_DEBUG, LOG_INFO, LOG_WARN are ignored.

# Turn off logging at run-time
If you read everything i mentioned above. You will understand one can turn-off logging at any time. In fact you can control which priority level logs to turn off using `log_set_level()` function.

# NOTE
This is all standard way of logging. There is nothing custom about it except that i have added TRACE macros only for developers so that they don't have to remove their sanity checks from their software manually. They will compile in release mode .. and there binary will be free from TRACE macros.

> I recall someone else suggesting turning the alternative definitions from `NULL` to `(void*)0`

`NULL` is defined to be equal to `(void*) 0` by the standard C library.  He suggested something else. We don't need to discuss that. But we can if you want in #1 issue.

**Comment by jgabaut** [comment]
If this (being able to turn the logging off at build time) **was** the only difference between `LOG` and `TRACE`, I'd be fine with this idea and just resort to never use `LOG` at all (really don't want this arbitrary restriction on how the user program just behave. If the builder wants to express "no logging AT ALL", it should be its right to do so.

**But**, this is actually not the only difference. `TRACE` has different not-configurable properties than `LOG` (ie: always report location) which make it a fundamentally different call (and that's completely fine and goes well with the design philosophy). 

Being a different call, resorting to using just the one and not the other (to ensure the "full-no-log" mode is available to user code, which would not be doable by using even a single `LOG`) is just not doable.

I really can't see any reason why this would not be something that user code can decide upon, while the default stays as it is (what I mean is that release mode won't disable `LOG` by default, if you care about this. But a separate macro for turning off `LOG` independently, or a similar mechanism, should be provided).

**Comment by khushal-banks** [comment]
do you want TRACE macro to control when to have location parameters?

**Comment by jgabaut** [comment]
> do you want TRACE macro to control when to have location parameters? similar to LOG macro.

Not really, I want to be able to achieve "log-off" mode as stated beforehand.

**Comment by khushal-banks** [comment]
You can use TRACE .. because you want them gone based on build setting.
I will change TRACE to have location parameters similar to how LOG controls them.

Would then TRACE be use able?

**Comment by khushal-banks** [comment]
> > do you want TRACE macro to control when to have location parameters? similar to LOG macro.
> 
> Not really, I want to be able to achieve "log-off" mode as a build config, as stated beforehand. Not using `LOG` at all sounds silly.

Please understand my concern here. If i make LOG go away it would be design flaw at my end. I want them to be always available.

**Comment by jgabaut** [comment]
> Please understand my concern here. If i make LOG go away it would be design flaw at my end. I want them to be always available.

I understand why you would want this to be the default for release mode.

I can't understand why it wouldn't be still possible to have `LOG` be a no-op from building user-code as such. User code can and will decide about this anyway.

**Comment by jgabaut** [comment]
> You can use TRACE .. because you want them gone based on build setting.
> I will change TRACE to have location parameters similar to how LOG controls them.
> 
> Would then TRACE be use able?

No, that would be besides the point. That was just an example on why they are not the same. One more thing to use as example (don't know if it's right but it's fitting) is that maybe `TRACE` calls handle the level logic differently. Are you also gonna make `TRACE` handle those just like `LOG`?

You can see why it would help, yes, but it would be besides the point.

**Comment by khushal-banks** [comment]
> maybe `TRACE` calls handle the level logic differently.

level logic is same

**Comment by khushal-banks** [comment]
> Just wrap `LOG` again in user-code

They are free to do so.

I only want following as standard:
- compile with -DNDEBUG and only LOG is available
- compile without -DNDEBUG and both LOG and TRACE are available

Because both of these compile time flags are standard. They are being used by every product. Including games, embedded and servers. So, they would not have to explicity define these. These compile time flags would exist in their compilation process already.

I don't want to write like ..
- compile with -DLOG_ENABLE or etc.

**Comment by jgabaut** [comment]
> I don't want to write like ..
> - compile with -DLOG_ENABLE or etc.

You don't have to. This a non-issue. Just add one #ifdef around the `LOG` definition with a custom config macro you can decide the name of. 
When it's not present, you get current behaviour. When it's present, you get `LOG` as no-op. This has nothing to do with the standard, as it can go on top of it. In both debug and release mode, you can turn off `LOG` calls. 

Why? Because that may be useful, to someone. Conversely, what use does it have, the effort blocking this tiny configuration?

If this is not something you thing can be added, close as wont-implement and go ahead with your day.

**Comment by khushal-banks** [comment]
LOG macro is for customers. No one is supposed to be disabled. 
**We want customers to see messages logged with LOG macro. Why would someone disable them?**

If someone don't want to supply with LOG then don't use it because it is made for that purpose.

If someone wants enable/disable feature.. then TRACE is more useful.
Difference in both macros will still be applicable.

Only difference is location parameters. Trace always prints them. 
LOG don't because we don't want customers to see file names with default LOG_LEVEL

This should be acceptable to everybody.
Otherwise, there is no point of making TRACE macro.

**Comment by khushal-banks** [comment]
> If this is not something you thing can be added, close as wont-implement and go ahead with your day. I can understand you wanting to keep things keen in your own way, so that's not a problem.

Bro your real requirement already exist. Use TRACE macro.
LOG macro has a different purpose. If we can disable LOG macro then TRACE will be useless.

**Comment by jgabaut** [comment]
> **We want customers to see messages logged with LOG macro. Why would someone disable them?**

You didn't answer my question about what use does this have. I could do the same, but I have a meaningful answer.

Why? Because user-code is not about logging, it's about business logic. If business logic requires a product to be able to be compiled with no logging at all in some cases, that has to be possible. That's a possible requirement, not even that weird. A log library whose logs can't be a build-time-configurable operation can't be used by any program that would like that as part of its configurations.

And mind, the library can actually be used, but requiring users to do the wrapping is just gonna drive that kind of user away.

Wrapping `LOG` again to disable the wrapper instead is not sane.

**Comment by jgabaut** [comment]
> LOG is always useful. 

Not if user-code want its product to be buildable in "no-log" mode without resorting to using only TRACE.

Say, I want to code with `LOG`, but I want to test a quick build and turn off all `LOG` calls (this is before release, so it's unrelated to most of your hints).

Can't do that. Why? No reason.

Don't suggest to use `TRACE` in this case, since the code actually wants to use `LOG`.
That would be not relevant.

And, in its release build, it probably won't turn off `LOG`.


If you can't see why your reasoning doesn't hold, I can't pull our more examples. Just close as wont-fix, I will understand.

**Comment by khushal-banks** [comment]
> I want to code with `LOG`, but I want to test a quick temporary build and turn off all `LOG` calls at build time

First of all you mentioned it is pre release and you don't want this in release so, Use TRACE .

Second, it is possible. Use priority levels. (link is mentioned in my first comment)

Log your temporary required information with
```
TRACE(LOG_DEBUG, "Some information");
```

then if you compile library with,
1. -DLOG_LEVEL=0 ... you will see this information
2. -DLOG_LEVEL=1 .. you will not see this information

**Comment by khushal-banks** [comment]
> Don't suggest to use `TRACE` in this case -That would be not relevant-, since the code actually wants to use `LOG`.

Then use LOG but then it will also be available in final release.
Just compile with -DLOG_LEVEL=0 to see it or any other level if you don't want to see it.

If you want to configure when do you want to see it at run time then use `log_set_level()` function and you can change when this get logged and ignored at run-time.

**Comment by khushal-banks** [comment]
> And, in its release build, it probably won't turn off `LOG`. But it may have its own usage reasons to turn off `LOG` when it wants.

It seems like your user want to compile code again and again. I am providing solution to his requirement with the help of [priority levels](https://github.com/khushal-banks/log_bank?tab=readme-ov-file#priority-level-support)

If he doesn't want to use TRACE for it's intended purpose then why would i change the library code. I can only suggest him to use TRACE.

And add a configuration portal to his main application which will use `log_set_level()` to change log level at run-time.
There is no need to recompile when user know what he wants.

Maybe all this will be easy to understand after #8 
I honestly believe that required functionality is supported. So closing this. 

I might reopen this if some other day i understand your requirement better.
I am really sorry that i couldn't be of much help. But i honestly believe [your required functionality exist](https://github.com/khushal-banks/log_bank/issues/29#issuecomment-2033504867)

**Comment by khushal-banks** [comment]
Removed the TRACE macro
and added the configuration of enabling or disabling LOG macro through [Generic-Make](https://github.com/khushal-banks/log_bank/blob/main/examples/Generic-Make) of the main application

Refer, new section of [COMPILATION.md](https://github.com/khushal-banks/log_bank/blob/main/docs/COMPILATION.md#compilation-flags-for-main-application) for details
