### ISSUE TITLE
[Feature request] Configurable header formatting

### ISSUE THREAD

**Issue by jgabaut** [khushal-banks/log_bank#4]
At the moment, the additional info provided by the log calls can be turned off in sections, but user code can't easily tweak the format at a global level (as far as I can tell).

I tried implementing something close to this. but three things held me back:

- The variety of arguments in the `location_header()` function. It makes deciding how to group them for the default `LOG_ARG()` macro difficult, since you would more likely have the vision to pick.
- The presence of the color_end argument as a needed argument to the string print function, since it is both needed and correct (only way of expressing more than one color per line) and a bit unsound (user code can turn off code but the color_end argument would still be there).
- The different format strings needed to also support the dim mode, since that branch needs an additional argument.

Main idea:

```c
#define LOG_FORMAT_STRING_DEFAULT "%s: %s()"

#ifndef LOG_FORMAT_STRING
#define LOG_FORMAT_STRING LOG_FORMAT_STRING_DEFAULT
#endif
```

Substitute the string literal for any of the currently default string format constants, and you get the idea.

There's a second, more hairy side to this:

```c
#define LOG_FORMAT_ARG_DEFAULT(stamp, color, name) (stamp), (color), (name)

#ifndef LOG_FORMAT_ARG
#define LOG_FORMAT_ARG(stamp, color, name LOG_FORMAT_ARG_DEFAULT((stamp), (color), (name))
#endif
```

I conveniently picked the easiest group of args since it's the base case for `default_header()`. But defining the current usage as a macro, to let users correctly override the header formatting, is not easy.

To see what would be the usage of these macros, check [this link](https://github.com/khushal-banks/log_bank/compare/main...jgabaut:log_bank:work/add-format-ifdef). I didn't open a pull request since my code was just an example, and didn't completely fulfill the intent.

What are your thoughts on this?

One must consider that a mismatched format-string/arg list is a bad usage example of this, but it can happen if a user decides to override the default formatting, if no compiler error is encountered.

**Comment by khushal-banks** [comment]
Hello @jgabaut, 
Thank you for posting this.

I have not made this format configurable because i wanted to provide uniformity of each and every logged message in every product which is using this library.

## Why ?
You already know my idea about creating a project named log_manage which would mange log-files generated using this log_bank library.

I support your idea as a requirement because i see many other library have this feature but you would have to convince me against my thoughts.

## Other problems with making header configurable
I already know your use case. So, i understand why you would like to change format of header.
Your solution will lead to following problems: (my personal opinion)
1. Solution is dependent on compile time variable like many other settings this library have. But it shouldn't be applicable for header. Header should be configurable at run-time (if allowed). So that main application (like your game) can change this in settings option without the need of recompilation. you agree?
2. This parameter is very rigid. Changing it to some wrong value may lead to issues. So, a lot of code would will written just to validate the configured pattern.

## Alternative (Very Flexible; suits best for your personal use case as well)
All thanks to you and you alone, we now have `log_retrieve` function.
We can also create one `log_parser` function with syntax:
```
extern int log_parser(char* message, size_t size, log_header_info_t* info);
```
This would be helpful in parsing previously saved logged message or new retrieved logged messages.
- It will separate header from message making message only contain logged information (without all header parameters)
- It will also separate all header parameters and return them in a structured way in `info` pointer argument.

```
// log_header_info_t structure:
/**
 *  \struct log_header_info_t
 *  \brief  Information required by header
 *
 *  \var log_header_info_t::stamp
 *  formatted time stamp of log request
 *
 *  \var log_header_info_t::color
 *  preassigned color based on priority of log request
 *
 *  \var log_header_info_t::name
 *  preassigned name based on priority of log request
 *
 *  \var log_header_info_t::locate
 *  location parameter of log request
 * /
 ```
having all these information separated main application can format the string as per there requirement.
It will make changing format available at run-time (no compilation required)

I am actually currently working on this (just started after #3)
Don't know for sure if this is doable easily or if i would make some changes to syntax or structure definition 
- maybe like changing everything in structure to string .. that can be more useful
- or adding more information

but i would like to know your perspective on how the proposed solution sound?
Would something similar to this be applicable to you?

**Comment by jgabaut** [comment]
I agree with the concerns about fragility, since I tried myself and was pointing out that there was a spiky side to my approach.

Your idea seems great, if I understood one thing correctly: run-time configuration means that user-code can call a configure function once (perhaps, just after initialising the library with the existing functions) and have all formats updated for every subsequent `LOG` or `TRACE` call.

Is this what you have in mind? I'm all for it. Sounds better than letting users define shady macros and trusting the ifdefs.

About the `log_parser`, I think it could have its uses, maybe even beyond what's being discussed. If you think it would be a useful addition, go ahead, it sounds you have a plan.

**Comment by khushal-banks** [comment]
> I'm now thinking if more than one configuration function would be needed, since there's a few formats being used and expressing all variables as parameters to a single, gigantic configure function for all of them at once doesn't sound right.
Maybe i am not sure.

> About the `log_parser`, I think it could have its uses, maybe even beyond what's being discussed.
Yes. It will provide user individual parameters. So, user would be able to check values and decide what logic to implement on their own.

Example: time parameter alone have many possible options like AM/PM, 12-24 hour format and HH:MM or HH:MM:SS
User may even need to calculate time like he may want to show notification like,
"This is what happened" - 24 min. ago

So, such endless possibilities can be handled by providing user the time parameter in a predefined format and then user can convert it on their own in their application software (independent of this library)

Same thing for colors, user may want to modify them like Change Red to light Red or even black depending own background color.

Location can be useless for some users and extremely useful for others.

So, if we go down this path of providing a function which can convert format we would fall down in a deep hole and no way to recover.

I agree parser is less useful. But it would be better to at least get some values out of a string which can be used to implement their conversion logic by themselves as it is specific to user. Do you agree?

**Comment by jgabaut** [comment]
I understand your concerns and I agree.

One thing I was wondering is if the parsed string could be optionally devoid of any escape sequence (what I mean is, a way to parse the log ensuring that the received string doens't contain color start or end codes).

**Comment by khushal-banks** [comment]
> A small note: I noticed the `color_end` definition being repeated twice in `log_banks.c`. It's enough times to switch its usage and define it as one of the library constants

I agree.


> (which is not against the purpose but skips over the fact that the log was not done with the wanted format in the first place).

100% agree.

> I'm now thinking if more than one configuration function would be needed

It would complicate the user to a point that he wouldn't understand what to choose. Plus, these functions would be small and similar. I will skip the feature addition if it turns out to be the only solution.

> run-time configuration means that user-code can call a configure function once (perhaps, just after initialising the library with the existing functions) and have all formats updated for every subsequent `LOG` or `TRACE` call

No. one function call for each conversion. Retrieve message then call parser. Retrieve message then call parser. again and again. And then on top of it ... use the parsed data to make their custom notification.

> One thing I was wondering is if the parsed string could be optionally devoid of any escape sequence (what I mean is, a way to parse the log ensuring that the received string doens't contain color start or end codes, possibly as a separate option on top of actually getting the string with codes and all).

Yes this is what i am trying to do. Converting string to variables. These variables will be returned to user through `log_parser`. Removing these escape sequences is the hardest part for me.. :) Then, user will use values as they suit their needs.

**Comment by jgabaut** [comment]
Couldn't the same mechanism used not to put escape codes in the files, be used to avoid including them in the messages that would be parsed?

**Comment by khushal-banks** [comment]
> Couldn't the same mechanism used not to put escape codes in the files, be used to avoid including them in the messages that would be parsed?

Great suggestion. It can be done by,
calling default_header/location_header two times. one time with colors and one time without.

I might sound silly but i might still choose to implement it some other way maybe using string library.
For me, additional features shouldn't pose work overload to existing features.

But your solution will work :)
